
export const SERVICES = [
    { id: 1, icon: "images/arbre_abattage.jpg", titre: 'PERMIS', options: ['Demande en ligne', 'Traitement', 'Emission', 'Mise à disposition du permis'], backgroundColor: 'rgba(216, 82, 33, 0.849)' },
    { id: 2, icon: "images/lettre_de_voiture.png", titre: 'LETTRES DE VOITUTRE', options: ['Enregistrement', 'Soumission', 'Impression'], backgroundColor: 'rgba(128, 128, 128, 0.828)' },
    { id: 3, icon: "images/certifat_legalite.jpg", titre: 'CERTIFICAT DE LEGALITE', options: ['Demande en ligne', 'Traitement', 'Emission', 'Mise à disposition du certificat'], backgroundColor: 'rgb(245, 210, 10)' },
    { id: 4, icon: "images/bulletin_specification.jpg", titre: 'BULLETIN DE SPECIFICATION DES BOIS A L\'EXPORT', options: ['Demande en ligne', 'Traitement', 'Emission', 'Mise à disposition du bulletin'], backgroundColor: 'rgba(74, 74, 238, 0.931)' },
    { id: 5, icon: "images/attestation_conformite.jpg", titre: 'ATTESTATION DE CONFORMITE DES PRODUITS', options: ['Demande en ligne', 'Traitement', 'Emission', 'Mise à disposition de l\'attestation'], backgroundColor: 'rgba(32, 92, 32, 0.924)' },
    { id: 6, icon: "images/autorisation_flegt.png", titre: 'AUTORISATION FLEGT', options: ['Demande en ligne', 'Traitement', 'Emission', 'Mise à disposition de l\'autorisation'], backgroundColor: 'rgb(219, 87, 34)' },
]

export const MODULES = [
    { id: 1, icon: './dossiericon/ressources/icons/iconADMINISTRATION_128x128.png', titre: "ADMINISTRATION", texte: "Définir les niveaux d'accès et les différents utilisateurs appelés à interagir avec l'application. Moucharder les opérations effectuées dans le système" },
    { id: 2, icon: './dossiericon/ressources/icons/iconDONNEES_128x128.png', titre: "DONNEES DE REFERENCE", texte: "Mettre en place le données de base du SIGIF devant servir de socle pour les autres modules de l'application" },
    { id: 3, icon: './dossiericon/ressources/icons/iconSIG_64x64.png', titre: "SIG", texte: "Visualiser les titres foretsiers et les opérations d'inventaire enregistrés  dans le système" },
    { id: 4, icon: './dossiericon/ressources/icons/iconTITRES_64x64.png', titre: "TITRES FORESTIERS", texte: "Gérer tous les types titres, leur documentation associée, ainsi que les opérations pouvant être effectuées: suspension, retrait, abandon, etc..." },
    { id: 5, icon: './dossiericon/ressources/icons/iconCODEBARRE_128x128.png', titre: "CODES BARRES", texte: "Gérer et suivre le numéros de code-barres  utilisés pour les inventaires, les abattage, les grumes, les clois  et la sécurisation des documents" },
    { id: 6, icon: './dossiericon/ressources/icons/iconINVENTAIRE_128x128.png', titre: "INVENTAIRES", texte: "Gérer les opérations liées aux travauxx d'inventaire: tracking des limites, inventaire et vérification, catalogues de produits" },
    { id: 7, icon: './dossiericon/ressources/icons/iconPERMIS_128x128.png', titre: "PERMIS", texte: "Gérer le processus d 'obtention de permis, de la demande jusqu'à l'emission et l'activation du permis" },
    { id: 8, icon: './dossiericon/ressources/icons/iconABATTAGE_128x128.png', titre: "ABATTAGES", texte: "Permettre à chaque opérateur d'enregistrer ses opérations d'abattage" },
    { id: 9, icon: './dossiericon/ressources/icons/iconCEMAC_128x128.png', titre: "BOIS CEMAC", texte: "Enregistrer et suivre les produits en provenancedes pays de la CEMAC en transit/importation sur le territoiore Camerounais" },
    { id: 10, icon: './dossiericon/ressources/icons/iconOPEPARC_128x128.png', titre: "OPERATIONS DE PARC", texte: "Gérer les mouvements de grumes et colis de débités dans les parcs" },
    { id: 11, icon: './dossiericon/ressources/icons/iconTRANSFORMATION_128x128.png', titre: "TRANSFORMATION", texte: "Gérer tout les processus de transformation jusqu'à l'obtention des colis de débités" },
    { id: 12, icon: './dossiericon/ressources/icons/iconFISCALITE_128x128.png', titre: "FISCALITE FORESTIERE", texte: "Générer les différents taxes liées à l'activité forestières et suivre leur recouvrement" },
    { id: 13, icon: './dossiericon/ressources/icons/iconCONTENTIEUX_128x128.png', titre: "CONTENCIEUX", texte: "Gérer et suivre les contencieux liés à l'activité forestière et initiés par le MINFOF" },
    { id: 14, icon: './dossiericon/ressources/icons/iconCERTIFLEGALITE_128x128.png', titre: "CERTIFICAT DE LEGALITE", texte: "Gérer les processus d'obtention du certificat de légalité, de la demande jusqu'à l'emission et l'activation  du certificat" },
    { id: 15, icon: './dossiericon/ressources/icons/iconEXPORTATION_128x128.png', titre: "EXPORTATIONS", texte: "Gérer les différents opérations liées à l'exploition des produits forestiers jusqu'à l'obtention de l'autorisation FLEGT" },
    { id: 16, icon: './dossiericon/ressources/icons/iconTRACABILITE_128x128.png', titre: "TRACABILITE", texte: "Tracer les produits forestiers et les documents émis par le système à travers leurs numéros de code-barres" },
    { id: 17, icon: './dossiericon/ressources/icons/iconRAPPORT_128x128.png', titre: "RAPPORT", texte: "Enregistrer les différents contrôles effectués par l'Administration forestière, compiler les données collectées sur le terrainn et produire les rapports" },
    { id: 18, icon: './dossiericon/ressources/icons/iconCONTROLE_128x128.png', titre: "CONTROLE", texte: "Produire les rapportds d'analyse de l'activité forestière et ceux demandés par l'annexe 7 de l'APV" },
]

export const ACTUALITES = [
    { id: 1, ressource: "Actualité", link: "#", titre: "Cérémonie d'inauguration du nouveau bâtiment abritant les services de la Délégation Département", src: "../../images/celcom25082021.jpg", description: "Le Ministre des Forêts et de la Faune, Monsieur Jules Doret NDONGO, présidera le vendredi 28 août 2021 à 10 heures à l'esplanade de la Délégation Départementale des Forêts et de la Faune de l'Océan à Kribi, la cérémonie d'inauguration du nouveau bâtiment abritant les services de ladite Délégation. Elle se fera dans le strict respect des mesures barrières contre le corona virus édictées par le Premier Ministre, Chef du Gouvernement." },
    { id: 2, ressource: "Vidéo", link: "#",  titre: "Douala-Cameroun: Concertation internationale sur la gestion de la transhumance des bovins", src: "../../images/ministre-minfof.jpg", description: "Chers internautes ,nous vous souhaitons la bienvenue sur le site officiel du Ministère des Forêts et de la faune. Nous espérons vivement que vous soyez les acteurs de notre organisation. En effet,nous sommes chargés de l'élaboration, de la mise en œuvre et de l'évaluation de la politique du Gouvernement en matière de forêt et de faune. A ce titre, nous avons pour responsabilité: -la gestion et la protection des forêts du domaine national ; - la mise au point et le contrôle de l'exécution des programmes de régénération, de reboisement, d'inventaire et d'aménagement des forêts ; - le contrôle du respect de la réglementation dans le domaine de l'exploitation forestière par les différents intervenants ; - la liaison avec les organismes professionnels du secteur forestier ; - l'aménagement et de la gestion des jardins botaniques ; - la mise en application des conventions internationales ratifiées par le Cameroun en matière de faune et de chasse." },
    { id: 3, ressource: "Vidéo", link: "#",  titre: "Le MINFOF Et TIKKI HYWOOD FOUNDATION Signent Un Mou", src: "../../images/DSC_actu.jpg", description: "Le Ministère des Forêts et de la Faune et la fondation TIKKI HYWOO ont signé le 25 juin 2021 à Yaoundé un mémorandum d’entente. Ce mémorandum d’entente, cadre de collaboration entre l’Etat du Cameroun et cette organisation, vise la conservation et la protection des espèces de pangolin au Cameroun. Les actions envisagées porteront sur: -La mise en place des infrastructures pour le sauvetage et la réhabilitation des pangolins -L’élaboration des campagnes médiatiques de sensibilisation concernant les espèces de pangolin -La mise en place d’un dispositif pour les recherches en cours en ce qui concerne les espèces de pangolin pour toute la durée du mémorandum d’entente -L’élaboration des projets d’inventaire ou biomonitoring sommaire relativement aux aires de réparation géographique des pangolins -Transfert de savoir/compétences aux termes des résultats obtenus par le centre de sauvetage et réhabilitation des pangolins -Le développement des activités génératrices de revenu au profit des populations autochtones et riveraines en alternative à la chasse et la consommation de la viande de brousse. -Au cours de la cérémonie le MINFOF était représenté par Jules Doret NDONGO, Chef de département et la Fondation par Mme Angellia Yound" },
    { id: 4, ressource: "Cérémonie", link: "#",  titre: "Cérémonie d’installation du groupe de travail interministériel", src: "../../images/IMG-2021.jpg", description: "Le Ministre des Forêts et de la Faune a installé, le 23 juin 2021 à Yaoundé le groupe de travail interministériel chargé de mener la réflexion sur le financement du Fonds Spécial de Développement Forestier et les autres réformes en cours relevant du sous-secteur forêt et faune. Présidé par Joseph Nyongwen, Secrétaire Général du MINFOF, ce Groupe de Travail, composite formé des représentants de diverses administrations, a aussitôt débuté ses travaux juste après cette cérémonie." },
    { id: 5, ressource: "Discours", link: "#",  titre: "Discours À L’occasion De La Position Des Organisations De La Société Civile Sur Le SIGIF2", src: "../../images/discours1.jpg", description: "Discours De Son Excellence Monsieur Jules Doret NDONGO, Ministre Des Forêts Et De La Faune Du Cameroun À L’occasion De La Présentation Officielle De La Position Des Organisations De La Société Civile Sur Le SIGIF 2 Télécharger le document" },
    { id: 6, ressource: "Actualité", link: "#",  titre: "La Société Civile Donne Sa Position Sur Le SIGIF2", src: "../../images/slide10.jpg", description: "Le Ministre des Forêts de la Faune M. Jules Doret Ndongo , a présidé le mardi 08 juin 2021 à la salle de Conférences du Ministère des Forêts de la Faune, la cérémonie de présentation officielle de la note de position des Organisations de la société Civile sur le Système Informatique de Gestion des informations Forestières de 2ème génération (SIGIF2). Initiée par un regroupement d’organisations de la société Civile, sous la bannière de la plateforme PFN-REDD+CC, représentée Mme Cécile NDJEBET, Coordinatrice nationale, cette cérémonie a été l’occasion des hôtes du Ministre de se prononcer officiellement à la suite des divergences manifestes affichées par les partenaires du Cameroun sur le développement du SIGIF 2. Les Organisations de la Société Civile (OSC) ont marqué globalement leur satisfaction sur cet outil tout en émettant le vœu d’un rapprochement des positions entre le Gouvernement Camerounais l’UE/Allemagne ainsi qu’au renforcement de l’outil technique. Cette position est aussi celle de Mme Cécile Ngomba, Directrice Nationale de WWF Cameroun qui, prenant la parole, en tant que partenaire technique, s’est positionnée en médiateur en prônant le dialogue entre le Gouvernement et ses partenaires. A la suite, le Ministre a présenté le SIGIF 2 « comme un outil novateur, catalyseur de la dématérialisation des procédures en matière d’exploitation forestière au Cameroun et de renforcement de la gouvernance sectorielle ». Il a apprécié cette démarche inédite pour des interlocuteurs habitués à manier la chicotte. Le chef de département a conclu son propos non sans marquer sa « gratitude pour l’accompagnement de la société civile dans tous les segments de l’activité sectorielle. Son apport est un cas pratique d’un partenariat basé sur la franchise, la méfiance mais de poursuite de l’intérêt commun. En tout temps, nous avons toujours voulu tous que les lignes bougent même si nous n’avons pas souvent les mêmes approches » a-t-il conclu. Evelyne MBOZOA" },
]

export const CRITERES = [
    { id: 1, texte: 'Légalité de l\'entité forestière', icon: './dossiericon/ressources/icons/iconCONTROLE_128x128.png' },
    { id: 2, texte: 'Suivi national de l\'activité forestière', icon: './dossiericon/ressources/icons/iconRAPPORT_128x128.png' },
    { id: 3, texte: 'Contrôle national de l\'activité forestière', icon: './dossiericon/ressources/icons/iconCONTENTIEUX_128x128.png' },
    { id: 4, texte: 'Conformité de chaîne d\'approvisionnement', icon: './dossiericon/ressources/icons/iconOPEPARC_128x128.png' },
    { id: 5, texte: 'Emission des autorisations FLEGT', icon: './dossiericon/ressources/icons/iconCODEBARRE_128x128.png' },
]